Port rejseplan
FahrplanDatenGarten/pyhafas pull request #11
Opened 2021-07-09 22:59 UTC by eisbaw

I've ported rejseplanen.dk to pyhafas.

Errata: Busses are labelled wrongly as trains, due to Leg's mode being trains by default.
But other than that, it seems to work.

I've also extended location queries to be more flexible than just Stations: Now one can ask from any address to any other address.

Motivation: I'm doing a digital dashboard with a Raspberry Pi Zero W.
It is not powerful enough to run Chromium(+Puppeteer), so scraping is a no-go.
pyhafas seems nice and extensible, and let's my Pi poll and display the next departures to my workplace :+1:

2021-07-10 13:23 UTC, n0emis approved these changes
Thanks for the contribution! LGTM 👍🏼

2021-07-10 17:54 UTC, em0lar requested changes
Hi, thanks for your contribution! A created a PATCH that should fix the failing tests (they fail because you've added `lid` to `Station`): https://gist.github.com/em0lar/c28fd830feb94a9f643b302473577f90 Please apply the PATCH or something else to let the tests pass.

2021-07-11 21:35 UTC, eisbaw commented
> Hi, thanks for your contribution! A created a PATCH that should fix the failing tests (they fail because you've added `lid` to `Station`): https://gist.github.com/em0lar/c28fd830feb94a9f643b302473577f90 Please apply the PATCH or something else to let the tests pass.

Thanks for the patch to fix the tests!
It's been squashed with the commit that adds lid, so everything is atomicly updated together :+1: 

And thanks for making pyhafas :-)

2021-07-12 07:21 UTC, em0lar approved these changes
LGTM

2021-07-12 07:22 UTC, merged